name: ethan manach
favicon: null
layout_spectrum: 0.24041
typography_spectrum: 0.21832
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6c7b5'
    - '#a29b93'
    - '#220821'
    - '#89797c'
    - '#573c4b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
